### ISSUE TITLE
Azcopy tab throws exception in file explorer

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#460]
Open Storage explorer in DIE1, Go to AZCopy tab, booom.
Looks like something is wrong in the Wiki service - could be wrong/bad url

```cs
Message
Object reference not set to an instance of an object.
Stack Trace
   at Datahub.Core.Services.Wiki.WikiService.LoadResourceTree() in /home/vsts/work/1/s/Portal/src/Datahub.Core/Services/Wiki/WikiService.cs:line 196
   at Datahub.Core.Services.Wiki.WikiService.LoadLanguageRoot(Boolean isFrench) in /home/vsts/work/1/s/Portal/src/Datahub.Core/Services/Wiki/WikiService.cs:line 269
   at Datahub.Portal.Components.EmbeddedWiki.OnInitializedAsync() in /home/vsts/work/1/s/Portal/src/Datahub.Portal/Components/EmbeddedWiki.razor:line 45
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by ErikApption** [comment]
I fixed the wiki exception - now we are down to a keyvault one
```cs
Message
Operation returned an invalid status code 'NotFound'
Stack Trace
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String vaultBaseUrl, String secretName, CancellationToken cancellationToken)
   at Datahub.Core.Services.Security.KeyVaultService.GetSecret(String secretName) in C:\code\SSC\datahub-portal\Portal\src\Datahub.Core\Services\Security\KeyVaultService.cs:line 43
   at Datahub.Core.Services.Storage.DataRetrievalService.GetProjectConnectionString(String accountName) in C:\code\SSC\datahub-portal\Portal\src\Datahub.Core\Services\Storage\DataRetrievalService.cs:line 76
   at Datahub.Core.Services.Storage.DataRetrievalService.GetBlobContainerClient(String project, String containerName) in C:\code\SSC\datahub-portal\Portal\src\Datahub.Core\Services\Storage\DataRetrievalService.cs:line 155
   at Datahub.Core.Services.Storage.DataRetrievalService.GetDelegationSasBlobUri(String container, String fileName, String projectUploadCode, Int32 days, BlobSasPermissions permissions, Boolean containerLevel) in C:\code\SSC\datahub-portal\Portal\src\Datahub.Core\Services\Storage\DataRetrievalService.cs:line 179
   at Datahub.Core.Services.Storage.DataRetrievalService.GenerateSasToken(String container, String projectUploadCode, Int32 daysValidity, Boolean containerLevel) in C:\code\SSC\datahub-portal\Portal\src\Datahub.Core\Services\Storage\DataRetrievalService.cs:line 232
   at Datahub.Portal.Pages.Project.FileExplorer.SASTokenButton.HandleSasButtonClick() in C:\code\SSC\datahub-portal\Portal\src\Datahub.Portal\Pages\Project\FileExplorer\SASTokenButton.razor:line 51
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by yjmrobert** [comment]
I'll take a look
