### ISSUE TITLE
Failure on overriding resource request

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#578]
### Bug type

DataHub Portal

### What happened?

After creating a new project and waiting for the pipelines to run and update the record in the terraform output queue, I tried creating a storage request from the override cards and it failed multiple time. Nothing was put on the queue or in the RP functions.

After refreshing the page and trying again it succeeded, it's possible there's some caching issue that's preventing an override. This could cause issues in any demos we are doing.

### Expected behavior

I would expect it to successfully create the request

### Reproduction steps

1. Create a new project
2. Wait for pipelines to run
3. Refresh page after they have run so that you no longer see the "Waiting on azure resource group" message
4. Click into the override menu
5. Click on request storage
6. Red failure appears

### Relevant log output

```shell
An exception occurred while iterating over the results of a query for context type 'Datahub.Core.Model.Datahub.DatahubProjectDBContext'.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Transactions.TransactionAbortedException: The transaction has aborted.
 ---> System.Transactions.TransactionPromotionException: Failure while attempting to promote transaction.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): There is already an open DataReader associated with this Connection which must be closed first.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransaction2005(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransaction(TransactionRequest transactionRequest, String name, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)
   at Microsoft.Data.SqlClient.SqlDelegatedTransaction.Promote()
ClientConnectionId:67993f21-534f-4c47-adc1-f290e9e27a2d
Error Number:-2,State:0,Class:11
ClientConnectionId before routing:78d16c39-628f-472a-8caa-8df95d2d45da
Routing Destination:d97487ac7bdb.tr4850.canadacentral1-a.worker.database.windows.net,11061
   --- End of inner exception stack trace ---
   at Microsoft.Data.SqlClient.SqlDelegatedTransaction.Promote()
   at System.Transactions.TransactionStatePSPEOperation.PSPEPromote(InternalTransaction tx)
   at System.Transactions.TransactionStateDelegatedNonMSDTC.EnterState(InternalTransaction tx)
   --- End of inner exception stack trace ---
   at System.Transactions.TransactionStateAborted.CheckForFinishedTransaction(InternalTransaction tx)
   at System.Transactions.EnlistableStates.PromotedToken(InternalTransaction tx)
   at System.Transactions.Transaction.GetPromotedToken()
   at InvokeStub_Transaction.GetPromotedToken(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.ActivateConnection(Transaction transaction)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by ErikApption** [comment]
Do we know what is causing this exception? there is nothing that traces back to our code

**Comment by iroelperez** [comment]
Check this line, should be Add not Attach.

[https://github.com/ssc-sp/datahub-portal/blob/771a182c27f102f19887a1096d4aca792e8ab792/Portal/src/Datahub.Infrastructure/Services/ProjectResourcingWhitelistService.cs#L58](https://github.com/ssc-sp/datahub-portal/blob/771a182c27f102f19887a1096d4aca792e8ab792/Portal/src/Datahub.Infrastructure/Services/ProjectResourcingWhitelistService.cs#L58)

**Comment by yjmrobert** [comment]
Wow nice catch, I'll make a PR

**Comment by yjmrobert** [comment]
Erik beat me to it lol, closing for now

**Comment by ErikApption** [comment]
Pushed hot fix.. issue was with Project entity - not WhiteList 
`context.Attach(projectResourceWhitelist.Project);`
