### ISSUE TITLE
Can't override a resource without enabling it first

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#616]
### Bug type

DataHub Portal

### What happened?

Getting an exception message when overriding a resource without toggling enable first

### Expected behavior

I should be able to override without enabling users to request the resource

### Reproduction steps

1. New workspace
2. Go to whitelist page
3. Request storage

### Relevant log output

```shell
WORKSPACES

RESOURCES

TOOLS

MY PROFILE

Something went wrong
TECHNICAL DETAILS
An application error has occurred on the DataHub server. The error has been recorded with Correlation ID 7c2e48e9-e634-48b2-ae32-8b74a45d78d1. To avoid network issues, if you are currently on the VPN, please try to disconnect the VPN and retry your actions.

AppInsights Query
exceptions
| where customDimensions.correlationId == '7c2e48e9-e634-48b2-ae32-8b74a45d78d1'
Message
The transaction is in doubt.
Stack Trace
   at System.Transactions.TransactionStateInDoubt.EndCommit(InternalTransaction tx)
   at System.Transactions.CommittableTransaction.Commit()
   at System.Transactions.TransactionScope.InternalDispose()
   at System.Transactions.TransactionScope.Dispose()
   at Datahub.ProjectTools.Services.RequestManagementService.HandleTerraformRequestServiceAsync(Datahub_Project project, String terraformTemplate) in /home/vsts/work/1/s/Portal/src/Datahub.ProjectTools/Services/RequestManagementService.cs:line 277
   at Datahub.Portal.Pages.Project.DataProject.DataProjectResources.ResourceWhitelist.AddResourceToQueue(Resource resource) in /home/vsts/work/1/s/Portal/src/Datahub.Portal/Pages/Project/DataProject/DataProjectResources/ResourceWhitelist.razor:line 148
   at Datahub.Portal.Pages.Project.DataProject.DataProjectResources.ResourceWhitelist.<>c__DisplayClass0_0.<<BuildRenderTree>b__10>d.MoveNext() in /home/vsts/work/1/s/Portal/src/Datahub.Portal/Pages/Project/DataProject/DataProjectResources/ResourceWhitelist.razor:line 36
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by yjmrobert** [comment]
iroel fixed this
