### ISSUE TITLE
🧩Conda support for Databricks

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#741]
Explore options to enable the installation of conda based packages
- [ ] #742
- [ ] #743

**Comment by simon-wang-gc** [comment]
Error when trying to run conda command in Databricks with Docker
```
org.apache.spark.SparkException: %pip/%conda commands are not supported on docker containers built with conda. To use %pip/%conda commands, use a virtualenv-based environment in your docker recipe, or use a default Databricks cluster.
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-1-912caa3ad434> in <module>
----> 1 get_ipython().run_line_magic('conda', 'list')

/databricks/python/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2325                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2326             with self.builtin_trap:
-> 2327                 result = fn(*args, **kwargs)
   2328             return result
   2329 

/databricks/python/lib/python3.8/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

/databricks/python/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/databricks/python_shell/dbruntime/PipMagicOverrides.py in conda(self, line)
     22     @line_magic
     23     def conda(self, line):
---> 24         self.pipMagicHandler.runCmd("conda", line)
     25 
     26     @line_magic

/databricks/python_shell/dbruntime/PipMagicOverrides.py in runCmd(self, magicCmd, line)
     34 
     35     def runCmd(self, magicCmd, line):
---> 36         envManager = self.entry_point.getNotebookScopedPythonEnvManager()
     37         parsedResult = envManager.parseCmd(magicCmd, line)
     38         if parsedResult.error():

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling t.getNotebookScopedPythonEnvManager.
: org.apache.spark.SparkException: %pip/%conda commands are not supported on docker containers built with conda. To use %pip/%conda commands, use a virtualenv-based environment in your docker recipe, or use a default Databricks cluster.
	at com.databricks.backend.daemon.driver.PythonDriverLocalBase$PythonEntryPointInterfaceImpl.getNotebookScopedPythonEnvManager(PythonDriverLocalBase.scala:427)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sean-Stilwell** [comment]
It looks to me like the Docker cluster runs it properly. I'm able to run `!conda list` and get all of the packages. I also ran `!conda install scikit-learn` and was able to use that package in my notebook.

**Comment by simon-wang-gc** [comment]
It looks like we can supply two versions of the Docker images that clients can choose from:

1. Purpose built Docker image specific to the project with Conda packages installed
2. Generic Docker image with only Conda installed and clients can provision their own environment with custom packages of choice.

**Comment by ErikApption** [comment]
@Sean-Stilwell  @simon-wang-gc  that is awesome - I'm thinking we should start with doing a small doc to explain how to setup the generic docker image but I'm sure the custom image will come handy soon.

**Comment by ErikApption** [comment]
@simon-wang-gc @Sean-Stilwell could we detail in https://github.com/ssc-sp/datahub-docs/blob/main/UserGuide/Databricks/Conda-Packages.md the steps you guys did to run the conda commands?
