### ISSUE TITLE
Resources sometimes fails in the new dev code

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#965]
### Bug type

DataHub Portal

### What happened?

1. Open Dev
2.  Error page opens with 
```
Object reference not set to an instance of an object.
   at Datahub.Portal.Layout.LearnSidebar.<BuildRenderTree>b__0_5(RenderTreeBuilder __builder5) in /home/vsts/work/1/s/Portal/src/Datahub.Portal/Layout/LearnSidebar.razor:line 21
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudNavMenu.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

### Expected behavior

Resource page opens without error

### Reproduction steps

1. Open resources on a rainy day in dev `https://dev.fsdh-dhsf.science.cloud-nuage.canada.ca/resource/`

### What browsers are you seeing the problem on?

Microsoft Edge

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by davidreneuw** [comment]
Its an issue with the sidebar crashing when resources are initializing. It's fixed in #963, specifically with commit [07780f4](https://github.com/ssc-sp/datahub-portal/pull/963/commits/07780f45c96757a9d4d3649fc6ea4b197675a51e)
